Text encoding methods
  -- OHE
  -- BOW
  -- n-grams
  -- TF-IDF

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"text":["people watch youtube","youtube watch youtube","people write comment","youtube write comment"],"output":[1,1,0,0]})

In [3]:
data.head()

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

**Bag of words**

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
BOW=CountVectorizer()

In [6]:
document_matrix=BOW.fit_transform(data["text"])

In [7]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [8]:
BOW.vocabulary_

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}

In [9]:
document_matrix[0].toarray()

array([[0, 1, 1, 0, 1]])

In [10]:
document_matrix[1].toarray()

array([[0, 0, 1, 0, 2]])

In [11]:
document_matrix[2].toarray()

array([[1, 1, 0, 1, 0]])

In [12]:
document_matrix[3].toarray()

array([[1, 0, 0, 1, 1]])

*Bigram*

In [13]:
bigram=CountVectorizer(ngram_range=(2,2))

In [14]:
bigramvocab=bigram.fit_transform(data["text"])

In [15]:
bigram.vocabulary_

{'people watch': 0,
 'watch youtube': 2,
 'youtube watch': 4,
 'people write': 1,
 'write comment': 3,
 'youtube write': 5}

*Trigram*

In [16]:
trigram=CountVectorizer(ngram_range=(3,3))

In [17]:
trigramdata=trigram.fit_transform(data["text"])

In [18]:
trigram.vocabulary_

{'people watch youtube': 0,
 'youtube watch youtube': 2,
 'people write comment': 1,
 'youtube write comment': 3}

In [19]:
mix=CountVectorizer(ngram_range=(1,2))

In [20]:
mix_vocab=mix.fit_transform(data["text"])

In [21]:
mix.vocabulary_

{'people': 1,
 'watch': 4,
 'youtube': 8,
 'people watch': 2,
 'watch youtube': 5,
 'youtube watch': 9,
 'write': 6,
 'comment': 0,
 'people write': 3,
 'write comment': 7,
 'youtube write': 10}

*tf-IDF*

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tfidf=TfidfVectorizer()

In [24]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [25]:
tfidf.get_feature_names_out()

array(['comment', 'people', 'watch', 'write', 'youtube'], dtype=object)

In [26]:
tfidf.idf_

array([1.51082562, 1.51082562, 1.51082562, 1.51082562, 1.22314355])